signet=1

[signet]
signetchallenge=0014a3ec9c731da66d9725d54947aede5c830623f33d
addnode=170.75.166.88:38333

# RPC
server=1
rpcuser=user
rpcpassword=password
rpcport=38332
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0

# REST interface
rest=1

# ZMQ for block/tx notifications
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28332

# Indexes
txindex=1
blockfilterindex=1
